name: OProject
description: Scientific Software
plugins: [jekyll-assets, jekyll-paginate, sass, github-pages, kramdown, rouge]
paginate: 10
baseurl: ''
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
