name: OProject
description: Scientific Software
plugins: [jekyll-assets, jekyll-paginate, jekyll-toc, sass, github-pages, kramdown, rouge]
markdown: kramdown
highlighter: rouge
paginate: 2
paginate_path: /page:num/
baseurl: ''
